### ISSUE TITLE
Malformed type

### ISSUE THREAD

**Issue by Amaury-Percq** [apptreesoftware/flutter_map#164] opened 2018-11-13 08:23 UTC
Hi, I am trying to run the example map but I get a "Malformed type" error.

I/flutter (30006): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30006): The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#31e03):
I/flutter (30006): Malformed type.
I/flutter (30006): 
I/flutter (30006): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (30006): more information in this error message to help you determine and fix the underlying cause.
I/flutter (30006): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (30006):   https://github.com/flutter/flutter/issues/new
I/flutter (30006): 
I/flutter (30006): When the exception was thrown, this was the stack:
I/flutter (30006): #0      new TileLayerOptions (package:flutter_map/src/layer/tile_layer.dart)
I/flutter (30006): #1      _MyHomePageState.build (file:///C:/Users/Amaury/AndroidStudioProjects/maptest/lib/main.dart:37:15)
And then it goes on for 255 lines.

Here is the code:
```
import 'package:flutter/material.dart';
import 'package:latlong/latlong.dart';
import 'package:flutter_map/flutter_map.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Flutter Map Test"),
      ),
      body: new FlutterMap(
        options: new MapOptions(
          center: LatLng(51.5, -0.09),
          zoom: 13.0,
        ),
        layers: [
          new TileLayerOptions(
            urlTemplate: "https://api.tiles.mapbox.com/v4/"
                "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
            additionalOptions: {
              'accessToken': 'pk.eyJ1IjoicXVpbnplIiwiYSI6ImNqb2Yyb2o4bDAwMW0za3A1bjNnd3VuMzUifQ.oCAMqyooC-ZrzebynSPFUA',
              'id': 'mapbox.streets',
            },
          ),
        ],
      ),
    );
  }
}
```

What have I done wrong ?

**Comment by ibrierley** [comment] 2018-11-13 09:31
Works for me fine with that code, what does your pubspec.yaml look like. Tried a full restart rather than a hot one ?

**Comment by Amaury-Percq** [comment] 2018-11-13 09:57
```
name: maptest
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_map: ^0.3.0
  latlong: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

```
I did try a full restart without result.

**Comment by ibrierley** [comment] 2018-11-13 13:15
Just out of interest, try creating a new flutter project with a different
name in Android Studio or whatever, and paste that code in there, nothing
else. See what happens.

**Comment by Amaury-Percq** [comment] 2018-11-13 14:09
What I showed you was already a new project but I did a third one just to be sure.
When I run that project, I first get two errors that I can fix by changing the Android tools and gradle versions. 
Then I get an error that, I believe, is linked to issue #154 
```compiler message: file:///C:/Users/Amaury/Documents/UTAR%20Project/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.3.0/lib/src/map/flutter_map_state.dart:34:3: Error: 'Stream' expects 0 type arguments. ```

(It is actually much longer than that and from what I understand, it is all about streams and types. I have saved it if it's of any help)
Then, without changing anything, I run the project again and that's when the "Malformed type" error happens.

So at this point, my guess is that there is nothing wrong with the code or the plugin (although that stream thing might be worth looking into). My Android Studio settings however must be completely messed up because I have a lot of compatibility issues that I don't really understand and I fix them by changing things here and there that I don't understand either.

**Comment by johnpryan** [comment] 2018-11-19 17:50
yes, please make sure you are using the latest stable version of the SDK and the latest version of the packages in your pubspec.yaml.  It's possible that we should move away from Stream<Null> and use Stream<void> instead https://github.com/apptreesoftware/flutter_map/blob/master/lib/src/map/flutter_map_state.dart#L34

**Comment by johnpryan** [comment] 2018-11-19 17:55
I'm going to mark this as a dupe of #154

**Closed by johnpryan** 2018-11-19 17:55 UTC
Labels: bug, question
